// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qfaoyuakvypkqlrjgcfj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFmYW95dWFrdnlwa3FscmpnY2ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4MjYyMDQsImV4cCI6MjA3MTQwMjIwNH0.NfHVMIc4PadkSGoJ08xA5oOZtu0-qe-Frozg9PYuTEo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});